import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ChakraProvider, Box, VStack, Grid, theme } from "@chakra-ui/react";
import { ColorModeSwitcher } from "../components/ColorModeSwitcher";
import { Logo } from "../components/Logo";
import { DAppProvider } from "../hooks/useDApp";
import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DAppProvider appName="Another app name">
        <ChakraProvider theme={theme}>
          <Layout>
            <ColorModeSwitcher justifySelf="flex-end" />
            <VStack spacing={8}>
              <Logo w={100} h={100} />
            </VStack>
          </Layout>
        </ChakraProvider>
      </DAppProvider>
    </div>
  )
}
